groups:
  review-group-all:
    members:
      - antgrutta
    required: 1
    paths:
      - "**"

  review-group-any:
    members:
      - shell-cat
      - proxy-cat
    required: 1
    paths:
      - "**"
