groups:
  review-group-all:
    members:
      - team:antgrutta-org/admins
    required: 1
    paths:
      - "**"

  review-group-any:
    members:
      - team:antgrutta-org/developers
    required: 1
    paths:
      - "**"
