name: CICD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-standard-workflow:
    uses: antgrutta-org/actions.workflows/.github/workflows/static-scan.yaml@main
    secrets: inherit
