name: Approvals

on:
  pull_request_review:
    types: [editted, submitted]

jobs:
  require_user_approval:
    name: Require User Approval
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: briancarnold/requireuserapproval@debug28
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/require_reviewers.yml
